spring:
  application:
    name: xyzp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xqpan?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    generator:
      #Long类型转换，防止精度丢失
      write_numbers_as_strings: true
  redis:
    host: 150.158.30.225
    password: lijunxi
    port: 6379
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    port: 587
    username: 2770063826@qq.com
    password: poxfodcacptudgbe
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
server:
  port: 8081


# 最大文件限制
multipart:
  maxFileSize: 3000MB
  maxRequestSize: 10000MB

# 默认分片大小
Chunk:
  size: 1024
